export const ATTACK_CONTROLS = [
  24, // INPUT_ATTACK
  69, // INPUT_VEH_ATTACK
  70, // INPUT_VEH_ATTACK2
  92, // INPUT_VEH_PASSENGER_ATTACK
  114, // INPUT_VEH_FLY_ATTACK
  121, // INPUT_VEH_FLY_ATTACK_CAMERA
  140, // INPUT_MELEE_ATTACK_LIGHT
  141, // INPUT_MELEE_ATTACK_HEAVY
  257, // INPUT_ATTACK2
  263, // INPUT_MELEE_ATTACK1
  264, // INPUT_MELEE_ATTACK2
  331, // INPUT_VEH_FLY_ATTACK2
] as const
